

export enum Keyword {
	AS = 'AS',
	SELECT = 'SELECT',
    ALL = 'ALL',
    DISTINCT = 'DISTINCT',
    DISTINCT_ON = 'DISTINCT ON',
    FROM = 'FROM',
    PREWHERE = 'PREWHERE',
    WHERE = 'WHERE',
    GROUP_BY = 'GROUP BY',
    WITH = 'WITH',
    RECURSIVE = 'RECURSIVE',
    TOTALS = 'TOTALS',
    HAVING = 'HAVING',
    WINDOW = 'WINDOW',
    QUALIFY = 'QUALIFY',
    ORDER_BY = 'ORDER BY',
    LIMIT = 'LIMIT',
    SETTINGS = 'SETTINGS',
    BY = 'BY',
    ROLLUP = 'ROLLUP',
    CUBE = 'CUBE',
    GROUPING_SETS = 'GROUPING SETS',
    TOP = 'TOP',
    WITH_TIES = 'WITH TIES',
    OFFSET = 'OFFSET',
    FETCH = 'FETCH',
    ONLY = 'ONLY',
    ROW = 'ROW',
    ROWS = 'ROWS',
    FIRST = 'FIRST',
    NEXT = 'NEXT',
    INTERPOLATE = 'INTERPOLATE',
}
